use std::fs;
use std::path::Path;

fn main() {
    // Load .env file from workspace root if it exists
    let env_path = Path::new("../.env");
    if env_path.exists() {
        dotenv::from_path(env_path).ok();
    } else {
        // Try root .env
        dotenv::dotenv().ok();
    }
    
    // Generate constants.rs from environment variables
    generate_constants();
}

fn generate_constants() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let constants_path = Path::new(&out_dir).join("constants.rs");
    
    let mut constants = String::from("// Auto-generated constants from .env file\n");
    constants.push_str("// DO NOT EDIT THIS FILE - it is generated at build time\n\n");
    
    // Helper function to get env var with default
    let get_env = |key: &str, default: &str, ty: &str| -> String {
        let value = std::env::var(key).unwrap_or_else(|_| default.to_string());
        match ty {
            "f64" => format!("pub(crate) const {}: f64 = {};\n", key, value),
            "f32" => format!("pub(crate) const {}: f32 = {};\n", key, value),
            "u64" => format!("pub(crate) const {}: u64 = {};\n", key, value),
            "u16" => format!("pub(crate) const {}: u16 = {};\n", key, value),
            "i64" => format!("pub(crate) const {}: i64 = {};\n", key, value),
            "i32" => format!("pub(crate) const {}: i32 = {};\n", key, value),
            "bool" => format!("pub(crate) const {}: bool = {};\n", key, value.to_lowercase()),
            _ => format!("pub(crate) const {}: &str = \"{}\";\n", key, value),
        }
    };
    
    // Motor/Mechanical Constants
    constants.push_str("// Motor/Mechanical Constants\n");
    constants.push_str(&get_env("MICROSTEPS", "25600.0", "f64"));
    constants.push_str(&get_env("GEAR_REDUCTION", "1.0", "f64"));
    constants.push_str(&get_env("SLEW_BEARING", "84.0", "f64"));
    constants.push_str(&get_env("DEFAULT_MAX_SPEED_STEPS_PER_S", "5000.0", "f32"));
    constants.push_str(&get_env("DEFAULT_ACCEL_STEPS_PER_S2", "200", "u16"));
    constants.push_str(&get_env("INVERT_MOTOR_DIRECTION", "true", "bool"));
    constants.push_str("\n");
    
    // Encoder Constants
    constants.push_str("// Encoder Constants\n");
    constants.push_str(&get_env("ENC_TICKS_PER_REV", "348323.0", "f32"));
    constants.push_str("\n");
    
    // Stall Detection
    constants.push_str("// Stall Detection\n");
    constants.push_str(&get_env("MAX_STEPS_WITHOUT_ENC_CHANGE", "20000", "i64"));
    constants.push_str(&get_env("ENCODER_OVERSHOOT_TOLERANCE_TICKS", "800", "i64"));
    constants.push_str(&get_env("ENCODER_STALL_MIN_TICKS", "400", "i32"));
    constants.push_str(&get_env("ENCODER_STALL_CHECK_INTERVAL_STEPS", "120000", "i64"));
    constants.push_str("\n");
    
    // Tracking Constants
    constants.push_str("// Tracking Constants\n");
    constants.push_str(&get_env("TRACKING_DEADBAND_DEG", "5.0", "f32"));
    constants.push_str(&get_env("HOME_HEADING_DEG", "90.0", "f32"));
    constants.push_str("\n");
    
    // Timezone
    constants.push_str("// Timezone\n");
    constants.push_str(&get_env("TIMEZONE_OFFSET_HOURS", "-5.0", "f32"));
    
    fs::write(&constants_path, constants).expect("Failed to write constants.rs");
    
    // Tell Cargo to rerun if .env changes
    println!("cargo:rerun-if-changed=../.env");
    println!("cargo:rerun-if-changed=.env");
}
