[package]
name = "motion"
version = "0.1.0"
edition = "2021"

[dependencies]
bno080 = { path = "../crates/sensors/bno080" }
accel-stepper = { path = "../crates/drivers/accel-stepper", features = ["hal", "std"] }
embedded-hal = "1.0.0"
esp-idf-svc = { version = "0.51", features = [
    "critical-section",
    "embassy-time-driver",
    "embassy-sync",
] }
log = "0.4"
chrono = { version = "0.4", features = ["clock"] }
semver = "1.0.26"               #New
astronav = { version = "0.2.5", features = ["noaa-sun"] }
clock = { path = "../crates/infrastructure/clock" }
network = { path = "../crates/infrastructure/network" }
ota = { path = "../crates/infrastructure/ota" }
wifi = { path = "../crates/infrastructure/wifi" }
quadrature-encoder = { version = "0.2.1", default-features = false }

[build-dependencies]
dotenv = "0.15"
