[package]
name = "ota"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
base64.workspace = true
embedded-svc.workspace = true
esp-idf-svc.workspace = true
heapless.workspace = true
hex = "0.4.3"
log.workspace = true
network.workspace = true
semver.workspace = true
serde_json.workspace = true
sha2 = "0.10.9"
