use std::{fs, path::Path};

fn main() {
    // Load .env file from workspace root if it exists
    let env_path = Path::new("../.env");
    if env_path.exists() {
        dotenv::from_path(env_path).ok();
    } else {
        // Try root .env
        dotenv::dotenv().ok();
    }

    // Generate constants.rs from environment variables
    generate_constants();
}

fn generate_constants() {
    let out_dir = std::env::var("OUT_DIR").expect("Cargo did not provide OUT_DIR");
    let constants_path = Path::new(&out_dir).join("constants.rs");

    let mut constants = String::from("// Auto-generated constants from .env file\n");
    constants.push_str("// DO NOT EDIT THIS FILE - it is generated at build time\n\n");

    // Helper function to get env var with default
    let get_env = |key: &str, default: &str, ty: &str| -> String {
        let value = std::env::var(key).unwrap_or_else(|_| default.to_string());
        match ty {
            "f64" => format!("pub(crate) const {}: f64 = {};\n", key, value),
            "f32" => format!("pub(crate) const {}: f32 = {};\n", key, value),
            "u64" => format!("pub(crate) const {}: u64 = {};\n", key, value),
            "u16" => format!("pub(crate) const {}: u16 = {};\n", key, value),
            "i64" => format!("pub(crate) const {}: i64 = {};\n", key, value),
            "i32" => format!("pub(crate) const {}: i32 = {};\n", key, value),
            "bool" => format!(
                "pub(crate) const {}: bool = {};\n",
                key,
                value.to_lowercase()
            ),
            _ => format!("pub(crate) const {}: &str = \"{}\";\n", key, value),
        }
    };

    // Motor/Mechanical Constants
    constants.push_str("// Motor/Mechanical Constants\n");
    constants.push_str(&get_env("INVERT_MOTOR_DIRECTION", "true", "bool"));
    constants.push('\n');

    // Timezone is DST-aware via runtime libc TZ/tzset (owned by runtime crate).
    // Motion reads local time via `chrono::Local`; no build-time offset needed.

    fs::write(&constants_path, constants).expect("Failed to write constants.rs");

    // Tell Cargo to rerun if .env changes
    println!("cargo:rerun-if-changed=../.env");
    println!("cargo:rerun-if-changed=.env");
}
