[package]
name = "motion"
version = "0.1.0"
edition = "2021"

[dependencies]
accel-stepper = { workspace = true, features = ["hal", "std"] }
anyhow.workspace = true
chrono = { workspace = true, features = ["clock"] }
clock.workspace = true
ds323x.workspace = true
embedded-hal.workspace = true
esp-idf-svc = { workspace = true, features = [
    "critical-section",
    "embassy-time-driver",
    "embassy-sync",
] }
log.workspace = true
network.workspace = true
ota.workspace = true
quadrature-encoder = { version = "0.2.1", default-features = false }
semver.workspace = true
serde_json.workspace = true
wifi.workspace = true

[build-dependencies]
dotenv.workspace = true
