use std::{fs, path::Path};

fn main() {
    // Set LD_LIBRARY_PATH for esp-clang to find libxml2.so.2 and other dependencies
    std::env::set_var("LD_LIBRARY_PATH", "/usr/lib64:/usr/lib");

    // Load .env file if it exists
    if Path::new(".env").exists() {
        dotenv::dotenv().ok();
    }

    // Generate constants.rs from environment variables
    generate_constants();

    embuild::espidf::sysenv::output();
}

fn generate_constants() {
    let out_dir = std::env::var("OUT_DIR").expect("Cargo did not provide OUT_DIR");
    let constants_path = Path::new(&out_dir).join("constants.rs");

    let mut constants = String::from("// Auto-generated constants from .env file\n");
    constants.push_str("// DO NOT EDIT THIS FILE - it is generated at build time\n\n");

    // Helper function to get env var with default
    let get_env = |key: &str, default: &str, ty: &str| -> String {
        let value = std::env::var(key).unwrap_or_else(|_| default.to_string());
        match ty {
            "f64" => format!("pub const {}: f64 = {};\n", key, value),
            "f32" => format!("pub const {}: f32 = {};\n", key, value),
            "u64" => format!("pub const {}: u64 = {};\n", key, value),
            "u32" => format!("pub const {}: u32 = {};\n", key, value),
            "u16" => format!("pub const {}: u16 = {};\n", key, value),
            "i32" => format!("pub const {}: i32 = {};\n", key, value),
            "i64" => format!("pub const {}: i64 = {};\n", key, value),
            "bool" => format!("pub const {}: bool = {};\n", key, value.to_lowercase()),
            "str" => format!("pub const {}: &str = \"{}\";\n", key, value),
            _ => format!("pub const {}: &str = \"{}\";\n", key, value),
        }
    };

    // Motor/Mechanical Constants
    constants.push_str("// Motor/Mechanical Constants\n");
    constants.push_str(&get_env("INVERT_MOTOR_DIRECTION", "true", "bool"));
    constants.push_str(&get_env("RELAY_ACTIVE_HIGH", "true", "bool"));
    constants.push_str(&get_env("LIMIT_SWITCH_ACTIVE_HIGH", "false", "bool"));
    constants.push('\n');

    // Operational Mode (as string constants for runtime conversion)
    constants.push_str("// Operational Mode\n");
    let profile = std::env::var("ACTIVE_PROFILE").unwrap_or_else(|_| "Normal".to_string());
    constants.push_str(&format!(
        "pub const ACTIVE_PROFILE_STR: &str = \"{}\";\n",
        profile
    ));
    let mode = std::env::var("ACTIVE_MODE").unwrap_or_else(|_| "Normal".to_string());
    constants.push_str(&format!(
        "pub const ACTIVE_MODE_STR: &str = \"{}\";\n",
        mode
    ));
    constants.push('\n');

    // WiFi Configuration
    constants.push_str("// WiFi Configuration\n");
    constants.push_str(&get_env("WIFI_SSID", "Power2", "str"));
    constants.push_str(&get_env("WIFI_PASSWORD", "@Powerfuture22", "str"));
    constants.push('\n');

    // NVS credential reset — force wifi_ssid/wifi_pass/tz_posix back to the
    // above .env defaults on every boot.
    constants.push_str("// NVS credential reset\n");
    constants.push_str(&get_env("RESET_NVS_CREDENTIALS", "true", "bool"));
    constants.push('\n');

    // Device identity (used as MQTT topic prefix: `tower/{device_id}/...`).
    // AWS IoT Core handles broker auth via TLS client certs, so no username /
    // password is plumbed here.
    constants.push_str("// Device Identity\n");
    constants.push_str(&get_env("DEVICE_ID", "10", "str"));
    constants.push('\n');

    // Timezone — DST-aware via libc setenv("TZ") + tzset. Fixed-offset constants
    // were removed in v1.1.0; TZ_POSIX alone drives all local-time conversion.
    let tz_posix =
        std::env::var("TZ_POSIX").unwrap_or_else(|_| "CST6CDT,M3.2.0,M11.1.0".to_string());
    constants.push_str("// POSIX TZ string for libc setenv/tzset (DST-aware local time)\n");
    constants.push_str(&format!("pub const TZ_POSIX: &str = {:?};\n", tz_posix));
    constants.push('\n');

    // Tower location (MQTT topic root is DEVICE_ID above).
    constants.push_str("// Tower location defaults\n");
    constants.push_str(&get_env("TOWER_LATITUDE", "32.797868", "f64"));
    constants.push_str(&get_env("TOWER_LONGITUDE", "-96.835597", "f64"));
    constants.push_str(&get_env("TOWER_ALTITUDE", "0.0", "f64"));
    constants.push('\n');

    fs::write(&constants_path, constants).expect("Failed to write constants.rs");

    // Tell Cargo to rerun if .env changes
    println!("cargo:rerun-if-changed=.env");
}
