use std::fs;
use std::path::Path;

fn main() {
    // Set LD_LIBRARY_PATH for esp-clang to find libxml2.so.2 and other dependencies
    std::env::set_var("LD_LIBRARY_PATH", "/usr/lib64:/usr/lib");
    
    // Load .env file if it exists
    if Path::new(".env").exists() {
        dotenv::dotenv().ok();
    }
    
    // Generate constants.rs from environment variables
    generate_constants();
    
    embuild::espidf::sysenv::output();
}

fn generate_constants() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let constants_path = Path::new(&out_dir).join("constants.rs");
    
    let mut constants = String::from("// Auto-generated constants from .env file\n");
    constants.push_str("// DO NOT EDIT THIS FILE - it is generated at build time\n\n");
    
    // Helper function to get env var with default
    let get_env = |key: &str, default: &str, ty: &str| -> String {
        let value = std::env::var(key).unwrap_or_else(|_| default.to_string());
        match ty {
            "f64" => format!("pub const {}: f64 = {};\n", key, value),
            "f32" => format!("pub const {}: f32 = {};\n", key, value),
            "u64" => format!("pub const {}: u64 = {};\n", key, value),
            "u32" => format!("pub const {}: u32 = {};\n", key, value),
            "u16" => format!("pub const {}: u16 = {};\n", key, value),
            "i32" => format!("pub const {}: i32 = {};\n", key, value),
            "i64" => format!("pub const {}: i64 = {};\n", key, value),
            "bool" => format!("pub const {}: bool = {};\n", key, value.to_lowercase()),
            "str" => format!("pub const {}: &str = \"{}\";\n", key, value),
            _ => format!("pub const {}: &str = \"{}\";\n", key, value),
        }
    };
    
    // Motor/Mechanical Constants
    constants.push_str("// Motor/Mechanical Constants\n");
    constants.push_str(&get_env("MICROSTEPS", "25600.0", "f64"));
    constants.push_str(&get_env("GEAR_REDUCTION", "1.0", "f64"));
    constants.push_str(&get_env("SLEW_BEARING", "84.0", "f64"));
    constants.push_str(&get_env("DEFAULT_MAX_SPEED_STEPS_PER_S", "5000.0", "f32"));
    constants.push_str(&get_env("DEFAULT_ACCEL_STEPS_PER_S2", "200", "u16"));
    constants.push_str(&get_env("INVERT_MOTOR_DIRECTION", "true", "bool"));
    constants.push_str("\n");
    
    // Encoder Constants
    constants.push_str("// Encoder Constants\n");
    constants.push_str(&get_env("ENC_TICKS_PER_REV", "348323.0", "f32"));
    constants.push_str("\n");
    
    // Stall Detection
    constants.push_str("// Stall Detection\n");
    constants.push_str(&get_env("MAX_STEPS_WITHOUT_ENC_CHANGE", "20000", "u64"));
    constants.push_str("\n");
    
    // Tracking Constants
    constants.push_str("// Tracking Constants\n");
    constants.push_str(&get_env("TRACKING_DEADBAND_DEG", "5.0", "f32"));
    constants.push_str(&get_env("HOME_HEADING_DEG", "90.0", "f32"));
    constants.push_str("\n");
    
    // Soft Limits
    constants.push_str("// Soft Limits (Safety Guardrails)\n");
    constants.push_str(&get_env("SOFT_LIMIT_MIN_DEG", "0.0", "f32"));
    constants.push_str(&get_env("SOFT_LIMIT_MAX_DEG", "285.0", "f32"));
    constants.push_str("\n");
    
    // Encoder Overshoot Protection
    constants.push_str("// Encoder Overshoot Protection (Safety)\n");
    constants.push_str(&get_env("ENCODER_OVERSHOOT_TOLERANCE_TICKS", "750", "i64"));
    constants.push_str("\n");
    
    // Operational Mode (as string constants for runtime conversion)
    constants.push_str("// Operational Mode\n");
    let profile = std::env::var("ACTIVE_PROFILE").unwrap_or_else(|_| "Normal".to_string());
    constants.push_str(&format!("pub const ACTIVE_PROFILE_STR: &str = \"{}\";\n", profile));
    let mode = std::env::var("ACTIVE_MODE").unwrap_or_else(|_| "Normal".to_string());
    constants.push_str(&format!("pub const ACTIVE_MODE_STR: &str = \"{}\";\n", mode));
    constants.push_str("\n");
    
    // WiFi Configuration
    constants.push_str("// WiFi Configuration\n");
    constants.push_str(&get_env("WIFI_SSID", "Power2", "str"));
    constants.push_str(&get_env("WIFI_PASSWORD", "@Powerfuture22", "str"));
    constants.push_str("\n");
    
    // MQTT Configuration
    constants.push_str("// MQTT Configuration\n");
    constants.push_str(&get_env("MQTT_USER", "device1", "str"));
    constants.push_str(&get_env("MQTT_PASSWORD", "1device", "str"));
    constants.push_str("\n");
    
    // Timezone
    constants.push_str("// Timezone\n");
    constants.push_str(&get_env("TIMEZONE_OFFSET_HOURS", "-5.0", "f32"));
    
    fs::write(&constants_path, constants).expect("Failed to write constants.rs");
    
    // Tell Cargo to rerun if .env changes
    println!("cargo:rerun-if-changed=.env");
}
