[package]
name = "sensors"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
embedded-hal.workspace = true
esp-idf-svc = { workspace = true, features = [
    "critical-section",
    "embassy-time-driver",
    "embassy-sync",
] }
hdc1080.workspace = true
log.workspace = true
