#!/bin/sh

# Add this file to your local .git/hooks to automatically check for valid formatting and compilation before commits

echo "Checking formatting..."
cargo fmt --check

if [ $? -ne 0 ]; then
    echo "Formatting issues detected."
    echo "Run 'cargo fmt' and try committing again."
    exit 1
fi

echo "Checking compilation..."
cargo build

if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
fi

exit 0