[package]
name = "hdc1080-test"
version = "0.1.0"
edition = "2021"

[package.metadata.esp-idf]
partition_table = "../../partitions.csv"

[[bin]]
name = "hdc1080-test"
path = "src/main.rs"
harness = false

[dependencies]
esp-idf-svc = { version = "0.51", features = [
    "critical-section",
    "embassy-time-driver",
    "embassy-sync",
] }
embedded-hal = "1.0.0"
anyhow = "1.0"
hdc1080 = { path = "../../crates/sensors/hdc1080" }

[build-dependencies]
embuild = "0.33.0"
