name: Build

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup ESP-IDF + Rust
        uses: ./.github/actions/esp-idf-setup

      - name: Build
        run: cargo build --workspace