name: Rust Format Check

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: cargo fmt --check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Rust environment
        uses: ./.github/actions/setup-rust

      - name: Check formatting
        run: cargo fmt --all -- --check