name: Format, Build & Clippy

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ESP_TARGET: esp32s3
  ESP_IDF_VERSION: v5.2.2

jobs:
  checks:
    name: Format, Build & Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup | Rust (Xtensa)
        if: ${{ env.ESP_TARGET == 'esp32' || env.ESP_TARGET == 'esp32s2' || env.ESP_TARGET == 'esp32s3' }}
        uses: esp-rs/xtensa-toolchain@v1.6
        with:
          default: true
          buildtargets: ${{ env.ESP_TARGET }}
          ldproxy: false

      - name: Setup | Rust (RISC-V)
        if: ${{ env.ESP_TARGET != 'esp32' && env.ESP_TARGET != 'esp32s2' && env.ESP_TARGET != 'esp32s3' }}
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          target: riscv32imc-unknown-none-elf
          components: rust-src

      - uses: Swatinem/rust-cache@v2

      - name: Setup | ESP-IDF
        shell: bash
        run: |
          git clone \
            --branch "${ESP_IDF_VERSION}" \
            --depth 1 \
            --recursive \
            https://github.com/espressif/esp-idf.git \
            "$HOME/esp-idf"

          "$HOME/esp-idf/install.sh" "${ESP_TARGET}"

      - name: Check formatting
        shell: bash
        run: |
          . "$HOME/esp-idf/export.sh"
          cargo fmt --all --check

      - name: Build workspace
        shell: bash
        run: |
          . "$HOME/esp-idf/export.sh"
          cargo build --locked --workspace

      - name: Run Clippy
        shell: bash
        run: |
          . "$HOME/esp-idf/export.sh"
          cargo clippy \
            --locked \
            --workspace \
            --all-targets \
            -- \
            -D warnings

      - name: Wokwi CI check
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          timeout: 10000
          expect_text: "Hello ESP-RS. https://github.com/esp-rs"
          fail_text: "Error"